name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      run: >
        sudo apt-get update &&
        sudo apt update &&
        sudo apt-get install -y build-essential && 
        sudo apt install -y libcunit1-dev libcmocka-dev
        
    - name: Build and run tests
      run: make test
